server:
  port: 8080
#  shutdown: graceful #Wait if it has any action
#  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/JWT
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  application:
    name: tracinglogs
elasticsearch:
  url: localhost:9200
springdoc:
  swagger-ui:
    path: /v1/swagger/index.html
  api-docs:
    path: /v1/swagger/api-docs
